//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатный (Free).
        /// </summary>
        internal static string AccountType_Basic {
            get {
                return ResourceManager.GetString("AccountType_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум (Plus).
        /// </summary>
        internal static string AccountType_Plus {
            get {
                return ResourceManager.GetString("AccountType_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        internal static string AccountType_Unknown {
            get {
                return ResourceManager.GetString("AccountType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить стрелку.
        /// </summary>
        internal static string AddArrow {
            get {
                return ResourceManager.GetString("AddArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить окружность.
        /// </summary>
        internal static string AddCircle {
            get {
                return ResourceManager.GetString("AddCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить прямоугольник.
        /// </summary>
        internal static string AddRectangle {
            get {
                return ResourceManager.GetString("AddRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить текст.
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннотация.
        /// </summary>
        internal static string AnnotateBubble {
            get {
                return ResourceManager.GetString("AnnotateBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелка.
        /// </summary>
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет границы.
        /// </summary>
        internal static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затемненность границы.
        /// </summary>
        internal static string BorderOpacity {
            get {
                return ResourceManager.GetString("BorderOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пт.
        /// </summary>
        internal static string BorderSizyType {
            get {
                return ResourceManager.GetString("BorderSizyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер границы.
        /// </summary>
        internal static string BorderWidth {
            get {
                return ResourceManager.GetString("BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднять выше.
        /// </summary>
        internal static string BringForward {
            get {
                return ResourceManager.GetString("BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднять наверх.
        /// </summary>
        internal static string BringToFront {
            get {
                return ResourceManager.GetString("BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить на Remby.
        /// </summary>
        internal static string Button_AddRemby {
            get {
                return ResourceManager.GetString("Button_AddRemby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор.
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть это окно.
        /// </summary>
        internal static string Button_CloseThisWindow {
            get {
                return ResourceManager.GetString("Button_CloseThisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дальше.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заново.
        /// </summary>
        internal static string Button_Reselect {
            get {
                return ResourceManager.GetString("Button_Reselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пометьте область для захвата.
        /// </summary>
        internal static string Capture_MarkArea {
            get {
                return ResourceManager.GetString("Capture_MarkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить цвет границы.
        /// </summary>
        internal static string ChangeBorderColor {
            get {
                return ResourceManager.GetString("ChangeBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить размер границы.
        /// </summary>
        internal static string ChangeBorderWidth {
            get {
                return ResourceManager.GetString("ChangeBorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить затемненность фигуры.
        /// </summary>
        internal static string ChangeFigureOpacity {
            get {
                return ResourceManager.GetString("ChangeFigureOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить порядок фигур.
        /// </summary>
        internal static string ChangeFiguresOrder {
            get {
                return ResourceManager.GetString("ChangeFiguresOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить цвет заливки.
        /// </summary>
        internal static string ChangeFillColor {
            get {
                return ResourceManager.GetString("ChangeFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить теги.
        /// </summary>
        internal static string ChangeTags {
            get {
                return ResourceManager.GetString("ChangeTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить цвет текста.
        /// </summary>
        internal static string ChangeTextColor {
            get {
                return ResourceManager.GetString("ChangeTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить шрифт текста.
        /// </summary>
        internal static string ChangeTextFont {
            get {
                return ResourceManager.GetString("ChangeTextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окружность.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клонировать.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клонировать выделнную фигуру.
        /// </summary>
        internal static string CloneSelectedFigure {
            get {
                return ResourceManager.GetString("CloneSelectedFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string ColorDialog_ApplyBtn {
            get {
                return ResourceManager.GetString("ColorDialog_ApplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синий.
        /// </summary>
        internal static string ColorDialog_Blue {
            get {
                return ResourceManager.GetString("ColorDialog_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зеленый.
        /// </summary>
        internal static string ColorDialog_Green {
            get {
                return ResourceManager.GetString("ColorDialog_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет HTML.
        /// </summary>
        internal static string ColorDialog_HTMLColor {
            get {
                return ResourceManager.GetString("ColorDialog_HTMLColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затемненность.
        /// </summary>
        internal static string ColorDialog_Opacity {
            get {
                return ResourceManager.GetString("ColorDialog_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавние цвета.
        /// </summary>
        internal static string ColorDialog_RecentColors {
            get {
                return ResourceManager.GetString("ColorDialog_RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красный.
        /// </summary>
        internal static string ColorDialog_Red {
            get {
                return ResourceManager.GetString("ColorDialog_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка цвета.
        /// </summary>
        internal static string ColorDialog_title {
            get {
                return ResourceManager.GetString("ColorDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаете ли вы что, вы можете перетянуть файлы на R иконку для их выгрузки?.
        /// </summary>
        internal static string ContextMessageFileDragging {
            get {
                return ResourceManager.GetString("ContextMessageFileDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаете ли вы, что вы можете добавлять материалы прямо на странице с помощью кнопки редактора &quot;Добавить&quot;?.
        /// </summary>
        internal static string ContextMessageRandom {
            get {
                return ResourceManager.GetString("ContextMessageRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте видео с  YouTube добавив его на странице редактора или перетягивайте видео прямо на иконку RembyCollector..
        /// </summary>
        internal static string ContextMessageUploadVideoFile {
            get {
                return ResourceManager.GetString("ContextMessageUploadVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаете ли вы что, вы можете перетянуть видео на R-иконку для выгрузки в Мои Материалы?.
        /// </summary>
        internal static string ContextMessageYouTubeRecording {
            get {
                return ResourceManager.GetString("ContextMessageYouTubeRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ввод.
        /// </summary>
        internal static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при попытке открытия видео..
        /// </summary>
        internal static string Error_LoadingVideo {
            get {
                return ResourceManager.GetString("Error_LoadingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка в процессе загрузки видео..
        /// </summary>
        internal static string Error_VideoUpload {
            get {
                return ResourceManager.GetString("Error_VideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фигура.
        /// </summary>
        internal static string FigureName {
            get {
                return ResourceManager.GetString("FigureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите &quot;Обзор&quot; что бы выбрать файлы для загрузки.
        /// </summary>
        internal static string FileUpload_HelpLabel {
            get {
                return ResourceManager.GetString("FileUpload_HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файлов.
        /// </summary>
        internal static string FileUpload_Title {
            get {
                return ResourceManager.GetString("FileUpload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет заливки.
        /// </summary>
        internal static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затемненность заливки.
        /// </summary>
        internal static string FillOpacity {
            get {
                return ResourceManager.GetString("FillOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не показывать в слудующий раз..
        /// </summary>
        internal static string FirstUserExperence_dontshow {
            get {
                return ResourceManager.GetString("FirstUserExperence_dontshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На следующем шаге, мы попросим Вас войти под вашим YouTube аккаунтом или создать новый..
        /// </summary>
        internal static string FirstUserExperience_body1 {
            get {
                return ResourceManager.GetString("FirstUserExperience_body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После загрузки видео, Вы можете использовать его на Remby выбрав &quot;Video&quot; на панели инструментов..
        /// </summary>
        internal static string FirstUserExperience_body2 {
            get {
                return ResourceManager.GetString("FirstUserExperience_body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby экранное видео.
        /// </summary>
        internal static string FirstUserExperience_FormTitle {
            get {
                return ResourceManager.GetString("FirstUserExperience_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что бы добавить видео на Remby, Вам нужно загрузить его на YouTube.
        /// </summary>
        internal static string FirstUserExperience_title {
            get {
                return ResourceManager.GetString("FirstUserExperience_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет шрифта.
        /// </summary>
        internal static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть окно.
        /// </summary>
        internal static string GettingStarted_Button_Close {
            get {
                return ResourceManager.GetString("GettingStarted_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаете ли вы что?.
        /// </summary>
        internal static string GettingStarted_DidYouKnow {
            get {
                return ResourceManager.GetString("GettingStarted_DidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не показывать при следующем запуске.
        /// </summary>
        internal static string GettingStarted_DontShowAgain {
            get {
                return ResourceManager.GetString("GettingStarted_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что все, что вы перенесете на серую R иконку, вверху экрана, будет доступно в &quot;My Content&quot; панели на сайте. Оттуда вы легко можете добавить это на страницы вашей книги.
        ///
        ///Попробуйте перенести картинку или текст с веб страницы, или файл с вашего рабочего стола..
        /// </summary>
        internal static string GettingStarted_Note1 {
            get {
                return ResourceManager.GetString("GettingStarted_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что все содержимое, которое вы загрузили, будет доступено в Remby редакторе во вкладке Recently uploaded для каждого типа?.
        /// </summary>
        internal static string GettingStarted_Note2 {
            get {
                return ResourceManager.GetString("GettingStarted_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы можете использовать клавиатуру для быстрого снятия снимков экрана или для начала записи видео?.
        /// </summary>
        internal static string GettingStarted_Note3 {
            get {
                return ResourceManager.GetString("GettingStarted_Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что пока идет запись видео, вы можете двигать изображение, выводимое с вебкамеры? И даже если вы передвинете его за зону записи видео, оно не будет отображаться на записи..
        /// </summary>
        internal static string GettingStarted_Note4 {
            get {
                return ResourceManager.GetString("GettingStarted_Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что пока идет запись видео с экрана, вы можете двигать область записи? Просто перетяните нижнюю панель в любую область, которую хотите записать. Вы так же можете двигать картинку в картинке (вывод с вебкамеры) или полностью ее отключить. Проведите мышей над видео с вебкамеры, что бы увидеть возможные действия..
        /// </summary>
        internal static string GettingStarted_Note5 {
            get {
                return ResourceManager.GetString("GettingStarted_Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string History_All {
            get {
                return ResourceManager.GetString("History_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При попытке изменить теги на сервере произошла ошибка. Пожалуйста, попробуйте повторить операцию позже..
        /// </summary>
        internal static string History_ChangeTagsError {
            get {
                return ResourceManager.GetString("History_ChangeTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще.
        /// </summary>
        internal static string History_Expand_List_Button {
            get {
                return ResourceManager.GetString("History_Expand_List_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы.
        /// </summary>
        internal static string History_Files {
            get {
                return ResourceManager.GetString("History_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать по тегам.
        /// </summary>
        internal static string History_FilterOnTags {
            get {
                return ResourceManager.GetString("History_FilterOnTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения.
        /// </summary>
        internal static string History_Images {
            get {
                return ResourceManager.GetString("History_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи: 1-{0} из {1}.
        /// </summary>
        internal static string History_Items_Count {
            get {
                return ResourceManager.GetString("History_Items_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string History_ListTitle {
            get {
                return ResourceManager.GetString("History_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string History_Refresh {
            get {
                return ResourceManager.GetString("History_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        internal static string History_Screenshot {
            get {
                return ResourceManager.GetString("History_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимки экрана.
        /// </summary>
        internal static string History_Screenshots {
            get {
                return ResourceManager.GetString("History_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string History_Screenvideo {
            get {
                return ResourceManager.GetString("History_Screenvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для изменения тегов выберите элемент.
        /// </summary>
        internal static string History_Select_To_Change_Tags {
            get {
                return ResourceManager.GetString("History_Select_To_Change_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста укажите элемент, которым вы хотите поделиться..
        /// </summary>
        internal static string History_SelectElementToShare {
            get {
                return ResourceManager.GetString("History_SelectElementToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все.
        /// </summary>
        internal static string History_ShowAll {
            get {
                return ResourceManager.GetString("History_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать файлы.
        /// </summary>
        internal static string History_ShowFiles {
            get {
                return ResourceManager.GetString("History_ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать изображения.
        /// </summary>
        internal static string History_ShowImages {
            get {
                return ResourceManager.GetString("History_ShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать снимки экранов.
        /// </summary>
        internal static string History_ShowScreenShots {
            get {
                return ResourceManager.GetString("History_ShowScreenShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать тексты.
        /// </summary>
        internal static string History_ShowTexts {
            get {
                return ResourceManager.GetString("History_ShowTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать видео.
        /// </summary>
        internal static string History_ShowVideos {
            get {
                return ResourceManager.GetString("History_ShowVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string History_Text {
            get {
                return ResourceManager.GetString("History_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тексты.
        /// </summary>
        internal static string History_Texts {
            get {
                return ResourceManager.GetString("History_Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string History_Videos {
            get {
                return ResourceManager.GetString("History_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string InfoBox_File {
            get {
                return ResourceManager.GetString("InfoBox_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы.
        /// </summary>
        internal static string InfoBox_Files {
            get {
                return ResourceManager.GetString("InfoBox_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        internal static string InfoBox_Link {
            get {
                return ResourceManager.GetString("InfoBox_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимок экрана.
        /// </summary>
        internal static string InfoBox_ScreenShoot {
            get {
                return ResourceManager.GetString("InfoBox_ScreenShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string InfoBox_Text {
            get {
                return ResourceManager.GetString("InfoBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка - {0}.
        /// </summary>
        internal static string InfoBox_UploadingWithParam {
            get {
                return ResourceManager.GetString("InfoBox_UploadingWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string InfoBox_Video {
            get {
                return ResourceManager.GetString("InfoBox_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ1.
        /// </summary>
        internal static string key1 {
            get {
                return ResourceManager.GetString("key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ2.
        /// </summary>
        internal static string key2 {
            get {
                return ResourceManager.GetString("key2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ3.
        /// </summary>
        internal static string key3 {
            get {
                return ResourceManager.GetString("key3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string LabelDelimiter {
            get {
                return ResourceManager.GetString("LabelDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет.
        /// </summary>
        internal static string NoBorder {
            get {
                return ResourceManager.GetString("NoBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не показывать это сообщение.
        /// </summary>
        internal static string NotificationDontShowAgain {
            get {
                return ResourceManager.GetString("NotificationDontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОРС.
        /// </summary>
        internal static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby Оптическое Распознавание Символов(ОРС) Изображения.
        /// </summary>
        internal static string OCR_FormTitle {
            get {
                return ResourceManager.GetString("OCR_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как улучшить качество ОРС.
        /// </summary>
        internal static string OCR_HowToImprove {
            get {
                return ResourceManager.GetString("OCR_HowToImprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество ОРС.
        /// </summary>
        internal static string OCR_Quality {
            get {
                return ResourceManager.GetString("OCR_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст скопирован в буфер обмена.
        /// </summary>
        internal static string OCR_TextCopied {
            get {
                return ResourceManager.GetString("OCR_TextCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптическое Распознавание Символов, ОСР, работает лучше с черным текстом на белом фоне и там где размер текста 12пунктов или больше. 
        ///В основном, простые шрифты считываются лучше, чем аккуратные написанные от руки.
        ///Картинка внутри захваченного изображения иногда интерпретируется как текст и в итоге получаются бессмысленные символы.
        ///Для лучшего результата сделайте следующее:
        ///-Удостоверьтесь, что вы копируете только 1 колонку за раз
        ///-Копируйте со страниц, где текст 12пунктов и больше
        ///-Копируйте со страни [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OCR_Tips {
            get {
                return ResourceManager.GetString("OCR_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извлеченный текст.
        /// </summary>
        internal static string OCR_Title1 {
            get {
                return ResourceManager.GetString("OCR_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (мы будем использовать этот текст для индексирования изображений на Remby).
        /// </summary>
        internal static string OCR_Title2 {
            get {
                return ResourceManager.GetString("OCR_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того что бы выделить область: 
        ///1. Нажмите и удерживайте кнопку мыши в левом верхнем углу желаемой области
        ///2. Переместите указатель в нижний правый угол области
        ///3. Отпустите кнопку мыши
        ///.
        /// </summary>
        internal static string OneClickScreenShot_Text {
            get {
                return ResourceManager.GetString("OneClickScreenShot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы кликнули 1 раз и RembyCollector сделал скриншот всего экрана..
        /// </summary>
        internal static string OneClickScreenShot_Title {
            get {
                return ResourceManager.GetString("OneClickScreenShot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затемненность.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла(max).
        /// </summary>
        internal static string Options_Account_FileSizeLimitLabel {
            get {
                return ResourceManager.GetString("Options_Account_FileSizeLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер хранилища(max).
        /// </summary>
        internal static string Options_Account_StorageSizeLimitLabel {
            get {
                return ResourceManager.GetString("Options_Account_StorageSizeLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип подписки.
        /// </summary>
        internal static string Options_Account_SubcriptionLabel {
            get {
                return ResourceManager.GetString("Options_Account_SubcriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой аккаунт.
        /// </summary>
        internal static string Options_Account_TabTitle {
            get {
                return ResourceManager.GetString("Options_Account_TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверять через.
        /// </summary>
        internal static string Options_Account_UpdatePeriodLabel {
            get {
                return ResourceManager.GetString("Options_Account_UpdatePeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика обновлений работающего приложения.
        /// </summary>
        internal static string Options_Account_UpdatePolicyLabel {
            get {
                return ResourceManager.GetString("Options_Account_UpdatePolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улучшить.
        /// </summary>
        internal static string Options_Account_UpgradeBtn {
            get {
                return ResourceManager.GetString("Options_Account_UpgradeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Пользователя.
        /// </summary>
        internal static string Options_Account_UserIdLabel {
            get {
                return ResourceManager.GetString("Options_Account_UserIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенные.
        /// </summary>
        internal static string Options_Advanced {
            get {
                return ResourceManager.GetString("Options_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to битрейт(Bits).
        /// </summary>
        internal static string Options_Audio_Bitrate {
            get {
                return ResourceManager.GetString("Options_Audio_Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бит на образец.
        /// </summary>
        internal static string Options_Audio_Bitspersample {
            get {
                return ResourceManager.GetString("Options_Audio_Bitspersample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каналы.
        /// </summary>
        internal static string Options_Audio_Channels {
            get {
                return ResourceManager.GetString("Options_Audio_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота образца(Hz).
        /// </summary>
        internal static string Options_Audio_Sample {
            get {
                return ResourceManager.GetString("Options_Audio_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук.
        /// </summary>
        internal static string Options_Audio_Title {
            get {
                return ResourceManager.GetString("Options_Audio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        internal static string Options_General {
            get {
                return ResourceManager.GetString("Options_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Options_Language_Title {
            get {
                return ResourceManager.GetString("Options_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать RembyCollector с.
        /// </summary>
        internal static string Options_Language_UseIn {
            get {
                return ResourceManager.GetString("Options_Language_UseIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вошел как.
        /// </summary>
        internal static string Options_LoggedIn {
            get {
                return ResourceManager.GetString("Options_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Options_Login {
            get {
                return ResourceManager.GetString("Options_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Options_LogOut {
            get {
                return ResourceManager.GetString("Options_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место вывод  статусных сообщений.
        /// </summary>
        internal static string Options_MsgBoxPlacement {
            get {
                return ResourceManager.GetString("Options_MsgBoxPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен.
        /// </summary>
        internal static string Options_NotLoggedIn {
            get {
                return ResourceManager.GetString("Options_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паказать в.
        /// </summary>
        internal static string Options_placeAt {
            get {
                return ResourceManager.GetString("Options_placeAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby аккаунт.
        /// </summary>
        internal static string Options_RembyAccount {
            get {
                return ResourceManager.GetString("Options_RembyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        internal static string Options_Reset {
            get {
                return ResourceManager.GetString("Options_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при сохранении конфигурации, пожалуйста убедитесь, что все измененные данные верны..
        /// </summary>
        internal static string Options_SaveDataError {
            get {
                return ResourceManager.GetString("Options_SaveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки сброшены до настроек по умолчанию.
        /// </summary>
        internal static string Options_SettingsRestored {
            get {
                return ResourceManager.GetString("Options_SettingsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход будет выполнен как только вы закроете приложение.
        /// </summary>
        internal static string Options_SignedOutNote {
            get {
                return ResourceManager.GetString("Options_SignedOutNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружать автоматически с Windows?.
        /// </summary>
        internal static string Options_StartWithWindows {
            get {
                return ResourceManager.GetString("Options_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый день.
        /// </summary>
        internal static string Options_Update_EveryDay {
            get {
                return ResourceManager.GetString("Options_Update_EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый час.
        /// </summary>
        internal static string Options_Update_EveryHour {
            get {
                return ResourceManager.GetString("Options_Update_EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждую неделю.
        /// </summary>
        internal static string Options_Update_EveryWeek {
            get {
                return ResourceManager.GetString("Options_Update_EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никогда.
        /// </summary>
        internal static string Options_Update_Never {
            get {
                return ResourceManager.GetString("Options_Update_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захват Видео.
        /// </summary>
        internal static string Options_Video {
            get {
                return ResourceManager.GetString("Options_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кадров в сек.
        /// </summary>
        internal static string Options_Video_FrameRate {
            get {
                return ResourceManager.GetString("Options_Video_FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string Options_Video_Title {
            get {
                return ResourceManager.GetString("Options_Video_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать видео приватным на YouTube?.
        /// </summary>
        internal static string Options_Video_YouTubePrivate {
            get {
                return ResourceManager.GetString("Options_Video_YouTubePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство.
        /// </summary>
        internal static string Options_Webcam_Device {
            get {
                return ResourceManager.GetString("Options_Webcam_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-камера.
        /// </summary>
        internal static string Options_Webcam_Title {
            get {
                return ResourceManager.GetString("Options_Webcam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижнем правом углу.
        /// </summary>
        internal static string Place_BottomRight {
            get {
                return ResourceManager.GetString("Place_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рядом с R иконкой.
        /// </summary>
        internal static string Place_NearIcon {
            get {
                return ResourceManager.GetString("Place_NearIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхнем правом углу.
        /// </summary>
        internal static string Place_TopRight {
            get {
                return ResourceManager.GetString("Place_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямоугольник.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby.
        /// </summary>
        internal static string Remby {
            get {
                return ResourceManager.GetString("Remby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Remby_Login_Title {
            get {
                return ResourceManager.GetString("Remby_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyCollector.
        /// </summary>
        internal static string RembyClipper {
            get {
                return ResourceManager.GetString("RembyClipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyCollector загрузка файлов.
        /// </summary>
        internal static string RembyFileUpload_WindowTitle {
            get {
                return ResourceManager.GetString("RembyFileUpload_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.remby.com.
        /// </summary>
        internal static string RembyLink {
            get {
                return ResourceManager.GetString("RembyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на Remby для создания аккаунта.
        /// </summary>
        internal static string RembyLogin_CreateAccount {
            get {
                return ResourceManager.GetString("RembyLogin_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет Remby аккаунта?.
        /// </summary>
        internal static string RembyLogin_DontHaveAccount {
            get {
                return ResourceManager.GetString("RembyLogin_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string RembyLogin_Password {
            get {
                return ResourceManager.GetString("RembyLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня?.
        /// </summary>
        internal static string RembyLogin_RememberMe {
            get {
                return ResourceManager.GetString("RembyLogin_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите под своим Remby аккаунтом.
        /// </summary>
        internal static string RembyLogin_Title {
            get {
                return ResourceManager.GetString("RembyLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или email.
        /// </summary>
        internal static string RembyLogin_Username {
            get {
                return ResourceManager.GetString("RembyLogin_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение скопировано в буфер обмена.
        /// </summary>
        internal static string RembyScreenshot_CopiedToClipboard {
            get {
                return ResourceManager.GetString("RembyScreenshot_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyCollector захваченное изображение.
        /// </summary>
        internal static string RembyScrennshot_WindowTitle {
            get {
                return ResourceManager.GetString("RembyScrennshot_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyCollector текст.
        /// </summary>
        internal static string RembyText_WindowTitle {
            get {
                return ResourceManager.GetString("RembyText_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string RembyVideo_Category {
            get {
                return ResourceManager.GetString("RembyVideo_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните теги..
        /// </summary>
        internal static string RembyVideo_CompeteTags {
            get {
                return ResourceManager.GetString("RembyVideo_CompeteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните описание..
        /// </summary>
        internal static string RembyVideo_CompleteDescription {
            get {
                return ResourceManager.GetString("RembyVideo_CompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните название..
        /// </summary>
        internal static string RembyVideo_CompleteTitle {
            get {
                return ResourceManager.GetString("RembyVideo_CompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string RembyVideo_Description {
            get {
                return ResourceManager.GetString("RembyVideo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby, Screen video.
        /// </summary>
        internal static string RembyVideo_TagsText {
            get {
                return ResourceManager.GetString("RembyVideo_TagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string RembyVideo_Title {
            get {
                return ResourceManager.GetString("RembyVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remby экранное видео -.
        /// </summary>
        internal static string RembyVideo_TitleText {
            get {
                return ResourceManager.GetString("RembyVideo_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyCollector экранное видео.
        /// </summary>
        internal static string RembyVideo_WindowTitle {
            get {
                return ResourceManager.GetString("RembyVideo_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружая свое видео, Вы подтверждаете что имеете права на содержимое или то что вы авторизованы правообладателем делать данное видео публичным на YouTube и что оно соответствует соглашениям предоставления услуг YouTube..
        /// </summary>
        internal static string RembyVideo_YouTubeLegal {
            get {
                return ResourceManager.GetString("RembyVideo_YouTubeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на YouTube что бы создать аккаунт.
        /// </summary>
        internal static string RembyYouTubeLogin_CreateAccount {
            get {
                return ResourceManager.GetString("RembyYouTubeLogin_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет YouTube аккаунта ?.
        /// </summary>
        internal static string RembyYouTubeLogin_DontHaveAccount {
            get {
                return ResourceManager.GetString("RembyYouTubeLogin_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как для бесплатного пользователя, ваше видео будет сохранено на YouTube.
        /// </summary>
        internal static string RembyYouTubeLogin_FreeUserTitle {
            get {
                return ResourceManager.GetString("RembyYouTubeLogin_FreeUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы будем держать сессию открытой до выхода из 
        ///RembyCollector. Мы не сохраним ваш пароль. Обещаем!.
        /// </summary>
        internal static string RembyYouTubeLogin_KeepLoggedIn {
            get {
                return ResourceManager.GetString("RembyYouTubeLogin_KeepLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, войдите под своим YouTube аккаунтом..
        /// </summary>
        internal static string RembyYouTubeLogin_Title {
            get {
                return ResourceManager.GetString("RembyYouTubeLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выделенную фигуру.
        /// </summary>
        internal static string RemoveFigure {
            get {
                return ResourceManager.GetString("RemoveFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реорганизация.
        /// </summary>
        internal static string Reorder {
            get {
                return ResourceManager.GetString("Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапуск приложения.
        /// </summary>
        internal static string RestartApplicationText {
            get {
                return ResourceManager.GetString("RestartApplicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опустить ниже.
        /// </summary>
        internal static string SendBackward {
            get {
                return ResourceManager.GetString("SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить назад.
        /// </summary>
        internal static string SendToBack {
            get {
                return ResourceManager.GetString("SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        internal static string ShareThis {
            get {
                return ResourceManager.GetString("ShareThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string ShareTo {
            get {
                return ResourceManager.GetString("ShareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и доступен(но) по адресу:.
        /// </summary>
        internal static string SuccessShare_AvailableAt {
            get {
                return ResourceManager.GetString("SuccessShare_AvailableAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шведский.
        /// </summary>
        internal static string SwedishLanguage {
            get {
                return ResourceManager.GetString("SwedishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теги.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для редактирования текста нажмите F2 или выполните двойной щелчок мыши..
        /// </summary>
        internal static string TextFigureText {
            get {
                return ResourceManager.GetString("TextFigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string TextType {
            get {
                return ResourceManager.GetString("TextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать в буфер обмена.
        /// </summary>
        internal static string ToolTip_Copy {
            get {
                return ResourceManager.GetString("ToolTip_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ОРС.
        /// </summary>
        internal static string ToolTip_OCR {
            get {
                return ResourceManager.GetString("ToolTip_OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить файл.
        /// </summary>
        internal static string ToolTip_Save {
            get {
                return ResourceManager.GetString("ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую книгу.
        /// </summary>
        internal static string TopNav_AddNewBook {
            get {
                return ResourceManager.GetString("TopNav_AddNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить текущую.
        /// </summary>
        internal static string TopNav_CancelCurrent {
            get {
                return ResourceManager.GetString("TopNav_CancelCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменено....
        /// </summary>
        internal static string TopNav_Canceled {
            get {
                return ResourceManager.GetString("TopNav_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить всё.
        /// </summary>
        internal static string TopNav_CancellAllUploading {
            get {
                return ResourceManager.GetString("TopNav_CancellAllUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить загрузку.
        /// </summary>
        internal static string TopNav_CancelUploading {
            get {
                return ResourceManager.GetString("TopNav_CancelUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захват изображения.
        /// </summary>
        internal static string TopNav_Capture {
            get {
                return ResourceManager.GetString("TopNav_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теги: {0} Изменить? {1:2}.
        /// </summary>
        internal static string TopNav_ChangeTagsWithParam {
            get {
                return ResourceManager.GetString("TopNav_ChangeTagsWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить обновление.
        /// </summary>
        internal static string TopNav_CheckForUpdates {
            get {
                return ResourceManager.GetString("TopNav_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить все.
        /// </summary>
        internal static string TopNav_ClearHistory {
            get {
                return ResourceManager.GetString("TopNav_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить список.
        /// </summary>
        internal static string TopNav_ClearList {
            get {
                return ResourceManager.GetString("TopNav_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите что бы добавить тег {0:2}.
        /// </summary>
        internal static string TopNav_ClickToAddTagWithParam {
            get {
                return ResourceManager.GetString("TopNav_ClickToAddTagWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string TopNav_Close {
            get {
                return ResourceManager.GetString("TopNav_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая очередь загрузки.
        /// </summary>
        internal static string TopNav_CurrentUploadingQueue {
            get {
                return ResourceManager.GetString("TopNav_CurrentUploadingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа которую вы используете не поддерживает технологию Drag-and-Drop. 
        ///Internet Explorer одна из таких программ
        ///При переходе на один из следующих браузеров: Google Chrome, 
        ///Mozilla Firefox or Apple Safari - вы будете иметь возможность исользовать технологию Drag-and-Drop..
        /// </summary>
        internal static string TopNav_DragAndDropDoesntSupported {
            get {
                return ResourceManager.GetString("TopNav_DragAndDropDoesntSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать Книгу на Remby.
        /// </summary>
        internal static string TopNav_EditBook {
            get {
                return ResourceManager.GetString("TopNav_EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема с сервером, повторите операцию позже.
        /// </summary>
        internal static string TopNav_Error {
            get {
                return ResourceManager.GetString("TopNav_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите выйти из RembyCollector?.
        /// </summary>
        internal static string TopNav_Exit {
            get {
                return ResourceManager.GetString("TopNav_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в Мои Remby Книги.
        /// </summary>
        internal static string TopNav_GoToMyBooks {
            get {
                return ResourceManager.GetString("TopNav_GoToMyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к Моим Материалам.
        /// </summary>
        internal static string TopNav_GoToMyStuff {
            get {
                return ResourceManager.GetString("TopNav_GoToMyStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте.
        /// </summary>
        internal static string TopNav_Hi {
            get {
                return ResourceManager.GetString("TopNav_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string TopNav_History {
            get {
                return ResourceManager.GetString("TopNav_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История обновлена.
        /// </summary>
        internal static string TopNav_HistoryRefreshed {
            get {
                return ResourceManager.GetString("TopNav_HistoryRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История (обновляется).
        /// </summary>
        internal static string TopNav_HistoryRefreshing {
            get {
                return ResourceManager.GetString("TopNav_HistoryRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть директорию лога.
        /// </summary>
        internal static string TopNav_OpenLogFolder {
            get {
                return ResourceManager.GetString("TopNav_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавние загрузки.
        /// </summary>
        internal static string TopNav_RecentUploadingItems {
            get {
                return ResourceManager.GetString("TopNav_RecentUploadingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить лог через скайп.
        /// </summary>
        internal static string TopNav_SendLogViaSkype {
            get {
                return ResourceManager.GetString("TopNav_SendLogViaSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отладочная информация сохранена на рабочий стоил в файле: {0}
        ///После того, как нажмете ОК, пожалуйста отошлите этот файл нам с помощью Skype. Спасибо..
        /// </summary>
        internal static string TopNav_SendSkypeMessageWithParam {
            get {
                return ResourceManager.GetString("TopNav_SendSkypeMessageWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткая ссылка URL: {0} была скопирована в буфер обмена..
        /// </summary>
        internal static string TopNav_ShortenUrlCopiedToClipBoardWithParam {
            get {
                return ResourceManager.GetString("TopNav_ShortenUrlCopiedToClipBoardWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать отладочный лог.
        /// </summary>
        internal static string TopNav_ShowDebugLog {
            get {
                return ResourceManager.GetString("TopNav_ShowDebugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string TopNav_Text {
            get {
                return ResourceManager.GetString("TopNav_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupproted extension - {0} ({1}).
        /// </summary>
        internal static string TopNav_UnsupportedExtension {
            get {
                return ResourceManager.GetString("TopNav_UnsupportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при попытке обновить приложение..
        /// </summary>
        internal static string TopNav_UpdateErrorMessage {
            get {
                return ResourceManager.GetString("TopNav_UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файлов.
        /// </summary>
        internal static string TopNav_Upload {
            get {
                return ResourceManager.GetString("TopNav_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружен(о).
        /// </summary>
        internal static string TopNav_Uploaded {
            get {
                return ResourceManager.GetString("TopNav_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string TopNav_Uploading {
            get {
                return ResourceManager.GetString("TopNav_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захват видео.
        /// </summary>
        internal static string TopNav_Video {
            get {
                return ResourceManager.GetString("TopNav_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to были загружены.
        /// </summary>
        internal static string TopNav_WereUploaded {
            get {
                return ResourceManager.GetString("TopNav_WereUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RembyСlipper загруженное видео.
        /// </summary>
        internal static string TopNav_YouTubeDescription {
            get {
                return ResourceManager.GetString("TopNav_YouTubeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруженное видео.
        /// </summary>
        internal static string TopNav_YouTubeTitle {
            get {
                return ResourceManager.GetString("TopNav_YouTubeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string Tray_About {
            get {
                return ResourceManager.GetString("Tray_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступая к работе.
        /// </summary>
        internal static string Tray_GettingStarted {
            get {
                return ResourceManager.GetString("Tray_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Tray_Options {
            get {
                return ResourceManager.GetString("Tray_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст.
        /// </summary>
        internal static string TypeYourTextHere {
            get {
                return ResourceManager.GetString("TypeYourTextHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление. Вы хотите обновить приложение сейчас?.
        /// </summary>
        internal static string Update_AvailableMessageWithQuestion {
            get {
                return ResourceManager.GetString("Update_AvailableMessageWithQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление.
        /// </summary>
        internal static string Update_AvailableText {
            get {
                return ResourceManager.GetString("Update_AvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление было отменено..
        /// </summary>
        internal static string Update_Cancelled {
            get {
                return ResourceManager.GetString("Update_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить последнюю версию приложения. Причина: \n{0}\nПожалуйста, сообщите об этой ошибке системному администратору..
        /// </summary>
        internal static string Update_CouldNotInstallLatestVersionWithParam {
            get {
                return ResourceManager.GetString("Update_CouldNotInstallLatestVersionWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы используете самую последнюю версию RembyCollector..
        /// </summary>
        internal static string Update_LatestVersionRunning {
            get {
                return ResourceManager.GetString("Update_LatestVersionRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение обнаружило обязательное обновление с текущей версии до версии {0}. Сейчас будет установлено обновление и произведен перезапуск приложения..
        /// </summary>
        internal static string Update_MandatoryUpdateWithParam {
            get {
                return ResourceManager.GetString("Update_MandatoryUpdateWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить новую версию приложения. Причина: \n{0}\nПожалуйста, сообщите об этой ошибке системному администратору..
        /// </summary>
        internal static string Update_NewVersionCouldNotBeRetreivedWithParam {
            get {
                return ResourceManager.GetString("Update_NewVersionCouldNotBeRetreivedWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление до последней версии было отменено..
        /// </summary>
        internal static string Update_UpdateToLatestVerWasCancelled {
            get {
                return ResourceManager.GetString("Update_UpdateToLatestVerWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение было обновлено. Выполнить перезапуск? (Если не выполнить перезапуск сейчас, то вы продолжите использовать текущую версию до следующего перезапуска).
        /// </summary>
        internal static string Update_WouldYouLikeToRestartMessage {
            get {
                return ResourceManager.GetString("Update_WouldYouLikeToRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить вывод видео камеры.
        /// </summary>
        internal static string VideoRecorder_CloseCam {
            get {
                return ResourceManager.GetString("VideoRecorder_CloseCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключить микрофон.
        /// </summary>
        internal static string VideoRecorder_MuteMic {
            get {
                return ResourceManager.GetString("VideoRecorder_MuteMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить вывод видео камеры.
        /// </summary>
        internal static string VideoRecorder_OpenCam {
            get {
                return ResourceManager.GetString("VideoRecorder_OpenCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать запись.
        /// </summary>
        internal static string VideoRecorder_StartRecording {
            get {
                return ResourceManager.GetString("VideoRecorder_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить запись.
        /// </summary>
        internal static string VideoRecorder_StopRecording {
            get {
                return ResourceManager.GetString("VideoRecorder_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить микрофон.
        /// </summary>
        internal static string VideoRecorder_UnmutMic {
            get {
                return ResourceManager.GetString("VideoRecorder_UnmutMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить  картинку в картинке.
        /// </summary>
        internal static string VideoRecorder_ZoomIn {
            get {
                return ResourceManager.GetString("VideoRecorder_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить картинку в картинке.
        /// </summary>
        internal static string VideoRecorder_ZoomOut {
            get {
                return ResourceManager.GetString("VideoRecorder_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть окна.
        /// </summary>
        internal static string Windows_Open {
            get {
                return ResourceManager.GetString("Windows_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимок экрана.
        /// </summary>
        internal static string Windows_Screenshot {
            get {
                return ResourceManager.GetString("Windows_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string Windows_Screenvideo {
            get {
                return ResourceManager.GetString("Windows_Screenvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль YouTube.
        /// </summary>
        internal static string YouTube_InvalidCredentials {
            get {
                return ResourceManager.GetString("YouTube_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка валидации данных. Пожалуйста проверьте заголовок, теги и т.д..
        /// </summary>
        internal static string YouTube_ValidationError {
            get {
                return ResourceManager.GetString("YouTube_ValidationError", resourceCulture);
            }
        }
    }
}
